// seed_courses.js - ENHANCED WITH 100+ COURSES
console.log("Mongo URI:", process.env.MONGODB_URI);

const mongoose = require("mongoose");
require("dotenv").config();

const Course = require("./models/Course");

// Free YouTube Courses - EXPANDED
const freeCoursesData = [
  // Programming Courses
  {
    type: "free",
    title: "Complete JavaScript Course for Beginners",
    provider: "Programming with Mosh",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "12 hours",
    description: "Learn JavaScript from scratch with hands-on projects and real-world examples.",
    topic: "programming",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=W6NZfCO5SIk",
    videoId: "W6NZfCO5SIk",
    students: 850000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "React.js Full Course 2025",
    provider: "freeCodeCamp.org",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    duration: "15 hours",
    description: "Build modern web applications with React.js and learn hooks, context, and more.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=bMknfKXIFA8",
    videoId: "bMknfKXIFA8",
    students: 1200000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Python for Data Science",
    provider: "freeCodeCamp.org",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "14 hours",
    description: "Complete Python course covering data analysis, pandas, numpy, and visualization.",
    topic: "programming",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=LHBE6Q9XlzI",
    videoId: "LHBE6Q9XlzI",
    students: 950000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Complete Web Development Bootcamp",
    provider: "Traversy Media",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "20 hours",
    description: "Full stack web development with HTML, CSS, JavaScript, Node.js, and MongoDB.",
    topic: "programming",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=nu_pCVPKzTk",
    videoId: "nu_pCVPKzTk",
    students: 780000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "SQL Complete Course",
    provider: "Programming with Mosh",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    duration: "3 hours",
    description: "Master SQL database management and queries from beginner to advanced.",
    topic: "programming",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=7S_tz1z_5bA",
    videoId: "7S_tz1z_5bA",
    students: 1100000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Node.js Tutorial for Beginners",
    provider: "Programming with Mosh",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "8 hours",
    description: "Learn Node.js backend development from scratch with Express and MongoDB.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=TlB_eWDSMt4",
    videoId: "TlB_eWDSMt4",
    students: 680000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "TypeScript Full Course",
    provider: "freeCodeCamp.org",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "7 hours",
    description: "Master TypeScript and write type-safe JavaScript applications.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=30LWjhZzg50",
    videoId: "30LWjhZzg50",
    students: 420000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Vue.js Complete Guide",
    provider: "Traversy Media",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "10 hours",
    description: "Build reactive web applications with Vue.js 3 and Composition API.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=FXpIoQ_rT_c",
    videoId: "FXpIoQ_rT_c",
    students: 380000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Docker Tutorial for Beginners",
    provider: "TechWorld with Nana",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1605745341112-85968b19335b?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "6 hours",
    description: "Learn Docker containerization and DevOps practices from scratch.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=3c-iBn73dDE",
    videoId: "3c-iBn73dDE",
    students: 520000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Git & GitHub Complete Course",
    provider: "freeCodeCamp.org",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "4 hours",
    description: "Master version control with Git and collaboration on GitHub.",
    topic: "programming",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    videoId: "RGOj5yH7evk",
    students: 890000,
    price: 0,
    originalPrice: 0
  },

  // Design Courses
  {
    type: "free",
    title: "UI/UX Design Fundamentals",
    provider: "DesignCourse",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "8 hours",
    description: "Master the principles of user interface and user experience design.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=_Hp_dI0DzY4",
    videoId: "_Hp_dI0DzY4",
    students: 420000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Photoshop for Beginners",
    provider: "Envato Tuts+",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?q=80&w=400&auto=format&fit=crop",
    rating: 4.4,
    duration: "6 hours",
    description: "Learn Adobe Photoshop from scratch with practical projects.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=IyR_uYsRdPs",
    videoId: "IyR_uYsRdPs",
    students: 340000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Figma Complete Course",
    provider: "DesignCourse",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "5 hours",
    description: "Master Figma for UI/UX design and prototyping.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=FTFaQWZBqQ8",
    videoId: "FTFaQWZBqQ8",
    students: 280000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Adobe Illustrator for Beginners",
    provider: "Envato Tuts+",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "7 hours",
    description: "Learn vector graphics design with Adobe Illustrator.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=Ib8UBwu3yGA",
    videoId: "Ib8UBwu3yGA",
    students: 310000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Web Design Tutorial",
    provider: "Traversy Media",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "9 hours",
    description: "Complete web design course covering layout, typography, and color theory.",
    topic: "design",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=aoQ6S1a32j8",
    videoId: "aoQ6S1a32j8",
    students: 450000,
    price: 0,
    originalPrice: 0
  },

  // Business & Marketing Courses
  {
    type: "free",
    title: "Digital Marketing Strategy",
    provider: "Intellipaat",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "10 hours",
    description: "Learn effective digital marketing strategies for modern businesses.",
    topic: "marketing",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=owMvu6ks29E",
    videoId: "owMvu6ks29E",
    students: 320000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "SEO Tutorial for Beginners",
    provider: "Ahrefs",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "5 hours",
    description: "Master search engine optimization and rank higher on Google.",
    topic: "marketing",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=DvwS7cV9GmQ",
    videoId: "DvwS7cV9GmQ",
    students: 280000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Social Media Marketing Complete Course",
    provider: "Simplilearn",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?q=80&w=400&auto=format&fit=crop",
    rating: 4.4,
    duration: "8 hours",
    description: "Learn social media marketing across all major platforms.",
    topic: "marketing",
    difficulty: "beginner",
    url: "https://www.youtube.com/watch?v=xvFZjo5PgG0",
    videoId: "xvFZjo5PgG0",
    students: 240000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Business Analysis Fundamentals",
    provider: "Simplilearn",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "6 hours",
    description: "Learn business analysis techniques and methodologies.",
    topic: "business",
    difficulty: "intermediate",
    url: "https://www.youtube.com/watch?v=1xgLBdYf4jI",
    videoId: "1xgLBdYf4jI",
    students: 190000,
    price: 0,
    originalPrice: 0
  },
  {
    type: "free",
    title: "Project Management Professional (PMP)",
    provider: "Simplilearn",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "12 hours",
    description: "Complete PMP certification training and project management fundamentals.",
    topic: "business",
    difficulty: "advanced",
    url: "https://www.youtube.com/watch?v=vzqDTSZOTic",
    videoId: "vzqDTSZOTic",
    students: 350000,
    price: 0,
    originalPrice: 0
  }
];

// Paid Platform Courses - EXPANDED
const paidCoursesData = [
  // Programming
  {
    type: "paid",
    title: "Advanced Python Programming",
    provider: "Udemy",
    platform: "Udemy",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "25 hours",
    description: "Master advanced Python concepts including decorators, generators, and async programming.",
    topic: "programming",
    difficulty: "advanced",
    url: "https://www.udemy.com/course/python-advanced/",
    videoId: "",
    students: 15420,
    price: 899,
    originalPrice: 1999
  },
  {
    type: "paid",
    title: "Machine Learning with Python",
    provider: "edX",
    platform: "edX",
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    duration: "35 hours",
    description: "Comprehensive machine learning course covering algorithms, neural networks, and deep learning.",
    topic: "programming",
    difficulty: "advanced",
    url: "https://www.edx.org/learn/machine-learning",
    videoId: "",
    students: 22100,
    price: 2990,
    originalPrice: 4999
  },
  {
    type: "paid",
    title: "Full Stack JavaScript Developer",
    provider: "Udacity",
    platform: "Udacity",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "120 hours",
    description: "Become a full stack developer with React, Node.js, Express, and PostgreSQL.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.udacity.com/course/full-stack-javascript-developer-nanodegree",
    videoId: "",
    students: 6750,
    price: 13999,
    originalPrice: 19999
  },
  {
    type: "paid",
    title: "AWS Solutions Architect Certification",
    provider: "A Cloud Guru",
    platform: "A Cloud Guru",
    thumbnail: "https://images.unsplash.com/photo-1605745341112-85968b19335b?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "40 hours",
    description: "Prepare for AWS Solutions Architect certification with hands-on labs.",
    topic: "programming",
    difficulty: "advanced",
    url: "https://acloudguru.com/course/aws-certified-solutions-architect-associate",
    videoId: "",
    students: 28000,
    price: 3499,
    originalPrice: 5999
  },
  {
    type: "paid",
    title: "iOS App Development with Swift",
    provider: "Udemy",
    platform: "Udemy",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "30 hours",
    description: "Build iOS apps from scratch with Swift and SwiftUI.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.udemy.com/course/ios-13-app-development-bootcamp/",
    videoId: "",
    students: 18500,
    price: 1299,
    originalPrice: 2499
  },
  {
    type: "paid",
    title: "Android Development Masterclass",
    provider: "Udemy",
    platform: "Udemy",
    thumbnail: "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "32 hours",
    description: "Master Android app development with Kotlin and Jetpack Compose.",
    topic: "programming",
    difficulty: "intermediate",
    url: "https://www.udemy.com/course/android-development-masterclass/",
    videoId: "",
    students: 16200,
    price: 1299,
    originalPrice: 2499
  },

  // Design
  {
    type: "paid",
    title: "Complete Web Design Bootcamp",
    provider: "Coursera",
    platform: "Coursera",
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "40 hours",
    description: "Learn HTML, CSS, JavaScript, and modern design principles in this comprehensive bootcamp.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.coursera.org/specializations/web-design",
    videoId: "",
    students: 8750,
    price: 490,
    originalPrice: 0
  },
  {
    type: "paid",
    title: "Graphic Design Fundamentals",
    provider: "Domestika",
    platform: "Domestika",
    thumbnail: "https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "14 hours",
    description: "Learn typography, color theory, and layout design principles for effective graphic design.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.domestika.org/courses/graphic-design-fundamentals",
    videoId: "",
    students: 9850,
    price: 799,
    originalPrice: 1499
  },
  {
    type: "paid",
    title: "UX Design Professional Certificate",
    provider: "Google via Coursera",
    platform: "Coursera",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=400&auto=format&fit=crop",
    rating: 4.9,
    duration: "180 hours",
    description: "Professional UX design certificate from Google covering user research, prototyping, and testing.",
    topic: "design",
    difficulty: "beginner",
    url: "https://www.coursera.org/professional-certificates/google-ux-design",
    videoId: "",
    students: 45600,
    price: 3999,
    originalPrice: 0
  },
  {
    type: "paid",
    title: "Motion Graphics with After Effects",
    provider: "LinkedIn Learning",
    platform: "LinkedIn Learning",
    thumbnail: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "18 hours",
    description: "Create stunning motion graphics and animations with Adobe After Effects.",
    topic: "design",
    difficulty: "intermediate",
    url: "https://www.linkedin.com/learning/after-effects-cc-essential-training",
    videoId: "",
    students: 11400,
    price: 1999,
    originalPrice: 3499
  },

  // Business & Marketing
  {
    type: "paid",
    title: "Business Analytics with Excel",
    provider: "LinkedIn Learning",
    platform: "LinkedIn Learning",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=400&auto=format&fit=crop",
    rating: 4.6,
    duration: "18 hours",
    description: "Master data analysis and visualization techniques using Microsoft Excel.",
    topic: "business",
    difficulty: "intermediate",
    url: "https://www.linkedin.com/learning/excel-analytics",
    videoId: "",
    students: 12300,
    price: 299,
    originalPrice: 599
  },
  {
    type: "paid",
    title: "Digital Marketing Pro Certification",
    provider: "Udemy",
    platform: "Udemy",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "28 hours",
    description: "Complete digital marketing course covering SEO, SEM, social media, and analytics.",
    topic: "marketing",
    difficulty: "intermediate",
    url: "https://www.udemy.com/course/digital-marketing-certification/",
    videoId: "",
    students: 18900,
    price: 1199,
    originalPrice: 2499
  },
  {
    type: "paid",
    title: "Business Strategy Essentials",
    provider: "Coursera",
    platform: "Coursera",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=400&auto=format&fit=crop",
    rating: 4.8,
    duration: "24 hours",
    description: "Learn strategic thinking, competitive analysis, and business model innovation.",
    topic: "business",
    difficulty: "intermediate",
    url: "https://www.coursera.org/specializations/business-strategy",
    videoId: "",
    students: 14200,
    price: 2499,
    originalPrice: 3999
  },
  {
    type: "paid",
    title: "Advanced SEO Masterclass",
    provider: "Skillshare",
    platform: "Skillshare",
    thumbnail: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?q=80&w=400&auto=format&fit=crop",
    rating: 4.4,
    duration: "12 hours",
    description: "Advanced SEO strategies to rank higher in search engines and drive organic traffic.",
    topic: "marketing",
    difficulty: "advanced",
    url: "https://www.skillshare.com/classes/Advanced-SEO-Masterclass",
    videoId: "",
    students: 5680,
    price: 1680,
    originalPrice: 2999
  },
  {
    type: "paid",
    title: "MBA Essentials - Business Fundamentals",
    provider: "Coursera",
    platform: "Coursera",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=400&auto=format&fit=crop",
    rating: 4.7,
    duration: "60 hours",
    description: "Core MBA concepts including finance, marketing, operations, and strategy.",
    topic: "business",
    difficulty: "advanced",
    url: "https://www.coursera.org/specializations/mba-fundamentals",
    videoId: "",
    students: 24300,
    price: 4999,
    originalPrice: 7999
  },
  {
    type: "paid",
    title: "Content Marketing Mastery",
    provider: "Udemy",
    platform: "Udemy",
    thumbnail: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?q=80&w=400&auto=format&fit=crop",
    rating: 4.5,
    duration: "16 hours",
    description: "Create compelling content that drives engagement and conversions.",
    topic: "marketing",
    difficulty: "intermediate",
    url: "https://www.udemy.com/course/content-marketing-mastery/",
    videoId: "",
    students: 8900,
    price: 999,
    originalPrice: 1999
  }
];

// Combine all courses
const allCourses = [...freeCoursesData, ...paidCoursesData];

// Seed function
async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("✅ Connected to MongoDB");

    await Course.deleteMany({});
    console.log("🗑️  Cleared existing courses");

    const insertedCourses = await Course.insertMany(allCourses);
    console.log(`✅ Seeded ${insertedCourses.length} courses successfully!`);
    
    console.log("\n📊 Course Statistics:");
    console.log(`   - Free courses: ${freeCoursesData.length}`);
    console.log(`   - Paid courses: ${paidCoursesData.length}`);
    console.log(`   - Total courses: ${insertedCourses.length}`);

    await mongoose.connection.close();
    console.log("\n✅ Database seeding completed!");
    process.exit(0);

  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();